"""empty message

Revision ID: 433a6d4d4349
Revises: e517bf577865
Create Date: 2021-01-26 21:00:11.197483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '433a6d4d4349'
down_revision = 'e517bf577865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('token_secret', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'token_secret')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
