"""empty message

Revision ID: c2c026da1c92
Revises: f38539b94370
Create Date: 2021-01-25 11:11:13.993700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2c026da1c92'
down_revision = 'f38539b94370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('discId', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'discId')
    # ### end Alembic commands ###
